<?php
namespace frontend\modules\clientintegr\modules\merc\helpers;

class MultiModel extends \yii\base\Model
{
  public static function loadMultiple($models, $data, $formName = null)
  {
      $class_name = get_class($models[0]);

      if ($formName === null) {
          /* @var $first Model|false */
          $first = reset($models);
          if ($first === false) {
              return false;
          }
          $formName = $first->formName();
      }

      for ($i = 0; $i < (count($data[$formName]) - count($models)); $i++) {

          $models[] = new $class_name;
      }

      return parent::loadMultiple($models, $data, $formName); // TODO: Change the autogenerated stub
  }
}