<?php

namespace api\common\models\merc;

use frontend\modules\clientintegr\modules\merc\helpers\api\cerber\cerberApi;
use Yii;

/**
 * This is the model class for table "{{%iiko_pconst}}".
 *
 * @property integer $id
 * @property integer $const_id
 * @property integer $org
 * @property string $value
 * @property string $created_at
 * @property string $updated_at
 *
 * @property iikoDicconst $const
 */
class mercPconst extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%merc_pconst}}';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_api');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['const_id', 'org'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['value'], 'string', 'max' => 255],
            [['value'], 'checkEnterpriseGuid'],
            [['const_id'], 'exist', 'skipOnError' => true, 'targetClass' => mercDicconst::className(), 'targetAttribute' => ['const_id' => 'id']],
        ];
    }

    public function checkEnterpriseGuid ($attribute, $params) {
       if($this->const_id != 10) {
           return;
       }
        if (!mercDicconst::checkSettings()) {
            $this->addError($attribute, "Нужно заполнить остальные настройки");
        }elseif (!cerberApi::getInstance()->checkRelationEnterproseGuidandIssuerID($this->value)) {
            $this->addError($attribute, "Указанное предприятие не связано с вашим ХС");
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'const_id' => Yii::t('app', 'Const ID'),
            'org' => Yii::t('app', 'Org'),
            'value' => Yii::t('app', 'Value'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function beforeSave($insert)
    {
        $this->value = trim($this->value);
        $const = $this->getConst()->one();
        if($const->denom == "hand_load_only")
            $this->value = empty($this->value) ? 0 : $this->value;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConst()
    {
        return $this->hasOne(mercDicconst::className(), ['id' => 'const_id']);
    }
}
