<?php

namespace api\common\models\merc;

use Yii;
use common\models\Organization;

/**
 * This is the model class for table "merc_service".
 *
 * @property integer      $id
 * @property integer      $org
 * @property string       $fd
 * @property string       $td
 * @property integer      $status_id
 * @property integer      $is_deleted
 * @property string       $object_id
 * @property integer      $user_id
 * @property string       $created_at
 * @property string       $updated_at
 * @property string       $code
 * @property string       $name
 * @property string       $address
 * @property string       $phone
 * @property Organization $organization
 */
class mercService extends \yii\db\ActiveRecord
{
    const STANDART_LICENSE_CODE = '1';
    const EXTENDED_LICENSE_CODE = '2';

    public static $licenses_list = [
        '1' => 'Стандартная лицензия',
        '2' => 'Расширенная лицензия',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'merc_service';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_api');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['org', 'status_id', 'is_deleted', 'user_id'], 'integer'],
            [['fd', 'td', 'created_at', 'updated_at'], 'safe'],
            [['object_id', 'phone'], 'string', 'max' => 45],
            [['code'], 'string', 'max' => 128],
            [['name', 'address'], 'string', 'max' => 255],
            [['org'], 'exist', 'skipOnError' => true, 'targetClass' => Organization::class, 'targetAttribute' => ['org' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'org'        => 'Организация MixCart',
            'fd'         => 'Активно с',
            'td'         => 'Активно по',
            'status_id'  => 'Статус',
            'is_deleted' => 'Is Deleted',
            'object_id'  => 'Object ID',
            'user_id'    => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'code'       => 'Code',
            'name'       => 'Название',
            'address'    => 'Address',
            'phone'      => 'Phone',
        ];
    }

    public function getOrganization()
    {
        return $this->hasOne(Organization::className(), ['id' => 'org']);
    }

    public function getOrganizationName()
    {
        return $this->organization ? $this->organization->name : 'no';
    }

    public function beforeSave($insert)
    {
        $this->code = $this->code ?? '1';
        if ($this->fd) {
            $this->fd = Yii::$app->formatter->asDate($this->fd, 'yyyy-MM-dd');
        }

        if ($this->td) {
            $this->td = Yii::$app->formatter->asDate($this->td, 'yyyy-MM-dd');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Лизензия
     *
     * @return iikoService|array|null|\yii\db\ActiveRecord
     */
    public static function getLicense($org_id)
    {
        return self::find()
            //->where(['status_id' => 2])
            ->andWhere('org = :org', ['org' => $org_id])
            //->andOnCondition('td >= NOW()')
            //->andOnCondition('fd <= NOW()')
            ->one();
    }
}
