<?php
namespace frontend\modules\clientintegr\modules\merc\helpers\api\dicts;

use frontend\modules\clientintegr\modules\merc\helpers\api\baseApi;
use Yii;

class dictsApi extends baseApi
{
    public function init()
    {
        $load = new Dicts();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getPurposeByGuid ($GUID)
    {
        $cache = Yii::$app->cache;
        $purpose = $cache->get('Purpose_'.$GUID);

        if(!($purpose === false))
            return $purpose;

        $client = $this->getSoapClient('dicts');
        $request = new getPurposeByGuidRequest();
        $request->guid = $GUID;
        $result = $client->GetPurposeByGuid($request);

        if(isset($result))
            $cache->add('Purpose_'.$GUID, $result, 60*60*24*7);
        return $result;
    }

    public function getUnitByGuid ($GUID)
    {
        $cache = Yii::$app->cache;
        $unit = $cache->get('Unit_'.$GUID);

        if(!($unit === false))
            return $unit;

        $client = $this->getSoapClient('dicts');

        $request = new getUnitByGuidRequest();
        $request->guid = $GUID;
        //var_dump($client->soapClient); die();
        $result = $client->GetUnitByGuid($request);

        if(isset($result))
            $cache->add('Unit_'.$GUID, $result, 60*60*24*7);
        return $result;
    }

    public function getUnitList ()
    {
        $client = $this->getSoapClient('dicts');

        $request = new getUnitListRequest();
        $result = $client->GetUnitList($request);

        return $result;
    }

    public function getPurposeList ($listOptions)
    {
        $client = $this->getSoapClient('dicts');

        $request = new getPurposeListRequest();
        $request->listOptions = $listOptions;
        $result = $client->GetPurposeList($request);

        return $result;
    }
}