<?php

namespace frontend\modules\clientintegr\modules\merc\helpers\api\ikar;

use frontend\modules\clientintegr\modules\merc\helpers\api\baseApi;
use Yii;

class ikarApi extends baseApi
{

    public function init()
    {
        $load = new Ikar();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getCountryByGuid($GUID)
    {
        $country = \common\models\vetis\VetisCountry::findOne(['guid' => $GUID]);
        
        if (!empty($country)) {
            return $country;
        }

        $client = $this->getSoapClient('ikar');
        $request = new getCountryByGuidRequest();
        $request->guid = $GUID;

        $result = $client->GetCountryByGuid($request);

        return $result;
    }

    public function getAllCountryList($listOptions = null)
    {
        $client = $this->getSoapClient('ikar');
        $request = new getAllCountryListRequest();
        if (isset($listOptions)) {
            $request->listOptions = $listOptions;
        }
        $result = $client->GetAllCountryList($request);
        return $result;
    }

}
