<?php

namespace frontend\modules\clientintegr\modules\merc\helpers\api\ikar;

use common\models\vetis\VetisCountry;
use frontend\modules\clientintegr\modules\merc\helpers\api\baseApi;

class ikarApi extends baseApi
{

    public function init()
    {
        $this->system = 'ikar';
        $this->wsdlClassName = Ikar::class;
        $_ = new \frontend\modules\clientintegr\modules\merc\helpers\api\ikar\Ikar();
        parent::init(); // TODO: Change the autogenerated stub
    }

    //Получние страны по GUID
    public function getCountryByGuid($GUID)
    {
       $country = VetisCountry::findOne(['guid' => $GUID]);
        
        if (!empty($country)) {
            return unserialize($country->data);
        }

        VetisCountry::getUpdateData($this->org_id);
        return null;
    }

    /**
     * Получение списка стран
     * @return \common\models\vetis\VetisUnit[]|null
     */
    public function getAllCountryList()
    {
        $countries = VetisCountry::findAll(['active' => 1, 'last' => 1]);

        if (!empty($countries)) {
            $list = [];
            foreach ($countries as $item)
            {
                $list = unserialize($item->data);
            }

            return $list;
        }

        VetisCountry::getUpdateData($this->org_id);
        return [];
    }

    /**
     * Составление запроса на загрузку справочника стран
     * @param $options
     * @return getCountryChangesListRequest
     * @throws Exception
     */
    public function getCountryChangesList($options)
    {
        require_once (__DIR__ ."/Ikar.php");
        $request = new getCountryChangesListRequest();
        if (array_key_exists('listOptions', $options)) {
            $request->listOptions = $options['listOptions'];
        }

        if (!array_key_exists('listOptions', $options)) {
            throw new \Exception('startDate field is not specified');
        }

        $request->updateDateInterval = new DateInterval();
        $request->updateDateInterval->beginDate = date('Y-m-d', strtotime($options['startDate'])) . 'T' . date('H:i:s', strtotime($options['startDate']));
        $request->updateDateInterval->endDate = date('Y-m-d') . 'T' . date('H:i:s') . '+03:00';

        return $request;
    }

}
