<?php

namespace frontend\modules\clientintegr\modules\merc\helpers\api\ikar;

use frontend\modules\clientintegr\modules\merc\helpers\api\baseApi;

class ikarApi extends baseApi
{

    public function init()
    {
        $load = new Ikar();
        $this->system = 'ikar';
        $this->wsdlClassName = Ikar::class;
        parent::init(); // TODO: Change the autogenerated stub
    }

    //Получние страны по GUID
    public function getCountryByGuid($GUID)
    {
       /*$country = \common\models\vetis\VetisCountry::findOne(['guid' => $GUID]);
        
        if (!empty($country)) {
            return $country;
        }*/

        $client = $this->getSoapClient('ikar');
        $request = new getCountryByGuidRequest();
        $request->guid = $GUID;

        $result = $client->GetCountryByGuid($request);

        return $result;
    }

    /**
     * Получение списка стран
     * @return \common\models\vetis\VetisUnit[]|null
     */
    public function getAllCountryList()
    {
        $units = \common\models\vetis\VetisCountry::findAll(['active' => 1, 'last' => 1]);

        if (!empty($units)) {
            return $units;
        }

        return null;
    }

    /**
     * Составление запроса на загрузку справочника стран
     * @param $options
     * @return getCountryChangesListRequest
     * @throws Exception
     */
    public function getCountryChangesList($options)
    {
        $request = new getCountryChangesListRequest();
        if (array_key_exists('listOptions', $options)) {
            $request->listOptions = $options['listOptions'];
        }

        if (!array_key_exists('listOptions', $options)) {
            throw new Exception('startDate field is not specified');
        }

        $request->updateDateInterval = new DateInterval();
        $request->updateDateInterval->beginDate = date('Y-m-d', strtotime($options['startDate'])) . 'T' . date('H:i:s', strtotime($options['startDate']));
        $request->updateDateInterval->endDate = date('Y-m-d') . 'T' . date('H:i:s') . '+03:00';

        return $request;
    }

}
