<?php
namespace frontend\modules\clientintegr\modules\merc\helpers\api\products;

use common\models\vetis\VetisProductByType;
use common\models\vetis\VetisProductItem;
use common\models\vetis\VetisSubproductByProduct;
use frontend\modules\clientintegr\modules\merc\helpers\api\baseApi;
use Yii;

class productApi extends baseApi
{
    public function init()
    {
        $this->system = 'product';
        $this->wsdlClassName = Products::class;
        $_ = new \frontend\modules\clientintegr\modules\merc\helpers\api\products\Products();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Получение записи продукта по GUID
     * @param $GUID
     * @return mixed|null
     */
    public function getProductByGuid ($GUID)
    {
        $product = VetisProductByType::findOne(['guid' => $GUID]);

        if(!empty($product)) {
            return unserialize($product->data);
        }

        VetisProductByType::getUpdateData($this->org_id);
        return null;
    }

    /**
     * Получение записи вида продукции по GUID
     * @param $GUID
     * @return mixed|null
     */
    public function getSubProductByGuid ($GUID)
    {
        $subProduct = VetisSubproductByProduct::findOne(['guid' => $GUID]);

        if(!empty($subProduct)) {
            return unserialize($subProduct->data);
        }

        VetisSubproductByProduct::getUpdateData($this->org_id);
        return null;
    }

    /**
     * Получение списка продуктов по типу
     * @param $type
     * @return mixed
     */
    public function getProductByTypeList ($type)
    {
        $result = VetisProductByType::find()->where(['productType' => $type])->all();

        if (!empty($result)) {
            $list = [];
            foreach ($result as $item)
            {
                $list[] = unserialize($item->data);
            }
            return $list;
        }

        VetisProductByType::getUpdateData(Yii::$app->user->identity->organization_id);
        return [];
    }

    /**
     * Получение списка видов продукции по продукту
     * @param $guid
     * @return mixed
     */
    public function getSubProductByProductList ($guid)
    {
        $result = VetisProductItem::find()->where(['productGuid' => $guid])->all();

        if (!empty($result)) {
            $list = [];
            foreach ($result as $item)
            {
                $list[] = unserialize($item->data);
            }
            return $list;
        }

        VetisProductItem::getUpdateData(Yii::$app->user->identity->organization_id);
        return [];
    }

    /**
     * Получение списка продуктов по виду и продукту
     * @param $productType
     * @param $product_guid
     * @param $subproduct_guid
     * @return mixed
     */
    public function getProductItemList  ($productType, $product_guid, $subproduct_guid)
    {
        $result = VetisProductItem::find()->where(['productType' => $productType, 'product_guid' => $product_guid, 'subproduct_guid' => $subproduct_guid])->all();

        if (!empty($result)) {
            $list = [];
            foreach ($result as $item)
            {
                $list[] = unserialize($item->data);
            }
            return $list;
        }

        VetisProductItem::getUpdateData(Yii::$app->user->identity->organization_id);
        return [];
    }

    /**
     * Составление запроса на списка предприятий мира
     * @param $options
     * @return getForeignEnterpriseChangesListRequest
     * @throws Exception
     */
    public function getProductChangesList ($options)
    {
        require_once (__DIR__ ."/Products.php");
        $request = new getProductChangesListRequest();
        if (array_key_exists('listOptions', $options)) {
            $request->listOptions = $options['listOptions'];
        }

        if (!array_key_exists('listOptions', $options)) {
            throw new \Exception('startDate field is not specified');
        }

        $request->updateDateInterval = new DateInterval();
        $request->updateDateInterval->beginDate = date('Y-m-d', strtotime($options['startDate'])) . 'T' . date('H:i:s', strtotime($options['startDate']));
        $request->updateDateInterval->endDate = date('Y-m-d') . 'T' . date('H:i:s') . '+03:00';

        return $request;
    }

    /**
     * Составление запроса на списка предприятий России
     * @param $options
     * @return getSubProductChangesListRequest
     * @throws Exception
     */
    public function getSubProductChangesList($options)
    {
        require_once (__DIR__ ."/Products.php");
        $request = new getSubProductChangesListRequest();
        if (array_key_exists('listOptions', $options)) {
            $request->listOptions = $options['listOptions'];
        }

        if (!array_key_exists('listOptions', $options)) {
            throw new Exception('startDate field is not specified');
        }

        $request->updateDateInterval = new DateInterval();
        $request->updateDateInterval->beginDate = date('Y-m-d', strtotime($options['startDate'])) . 'T' . date('H:i:s', strtotime($options['startDate']));
        $request->updateDateInterval->endDate = date('Y-m-d') . 'T' . date('H:i:s') . '+03:00';

        return $request;
    }

    /**
     * Составление запроса на списка ХС России
     * @param $options
     * @return getProductItemChangesListRequest
     * @throws Exception
     */
    public function getProductItemChangesList($options)
    {
        require_once (__DIR__ ."/Products.php");
        $request = new getProductItemChangesListRequest();
        if (array_key_exists('listOptions', $options)) {
            $request->listOptions = $options['listOptions'];
        }

        if (!array_key_exists('listOptions', $options)) {
            throw new \Exception('startDate field is not specified');
        }

        $request->updateDateInterval = new DateInterval();
        $request->updateDateInterval->beginDate = date('Y-m-d', strtotime($options['startDate'])) . 'T' . date('H:i:s', strtotime($options['startDate']));
        $request->updateDateInterval->endDate = date('Y-m-d') . 'T' . date('H:i:s') . '+03:00';

        return $request;
    }
}