<?php

namespace frontend\widgets\multiCheck;

class CheckboxColumn extends \yii\grid\CheckboxColumn
{
    public function renderHeaderCellContent()
    {
        /*if ($this->headerOptions instanceof Closure) {
            $this->headerOptions = call_user_func($this->headerOptions, $model, $key, $index, $this);
        }*/
        return parent::renderHeaderCellContent(); // TODO: Change the autogenerated stub
    }
}